global:
  scrape_interval: 15s

scrape_configs:
  # VictoriaMetrics itself
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']
    scrape_interval: 10s
    metrics_path: /metrics

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # VMAuth metrics
  - job_name: 'vmauth'
    static_configs:
      - targets: ['vmauth:8427']
    scrape_interval: 15s
    metrics_path: /metrics

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics