global:
  scrape_interval: 15s

scrape_configs:
  # VictoriaMetrics itself
  - job_name: "victoriametrics"
    static_configs:
      - targets: ["victoriametrics:8428"]
    scrape_interval: 10s
    metrics_path: /metrics

  # Node Exporter for system metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 15s
    metrics_path: /metrics

  # VMAuth metrics
  - job_name: "vmauth"
    static_configs:
      - targets: ["vmauth:8427"]
    scrape_interval: 15s
    metrics_path: /metrics

  # Grafana metrics
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: "nas-node-exporter"
    static_configs:
      - targets: ["192.168.86.201:9100"]
    scrape_interval: 15s

  # Traefik metrics (enabled with Prometheus configuration)
  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8080"]
    scrape_interval: 15s
    metrics_path: /metrics

  # cAdvisor for Docker container metrics
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: "mira-desktop"
    static_configs:
      - targets:
          - "192.168.86.200:9100"
    scrape_interval: 30s

  - job_name: "xps-17"
    static_configs:
      - targets:
          - "192.168.86.204:9100"
    scrape_interval: 30s

  # Kleio service metrics
  - job_name: "kleio"
    static_configs:
      - targets: ["kleio:8080"]
    scrape_interval: 15s
    metrics_path: /metrics

  # Technitium DNS Server metrics
  - job_name: "technitium-dns"
    static_configs:
      - targets: ["technitium-exporter:4001"]
    scrape_interval: 15s
    metrics_path: /metrics
